version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - MrBean355
  assignees:
  - MrBean355
  ignore:
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - "> 1.4.3, < 1.5"
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-test
    versions:
    - "> 1.4.3, < 1.5"
  - dependency-name: net.dv8tion:JDA
    versions:
    - 4.2.0_230
    - 4.2.0_236
    - 4.2.0_239
    - 4.2.0_241
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - 1.4.2-native-mt
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-test
    versions:
    - 1.4.2-native-mt
