language: java
install: true
jdk: oraclejdk8
dist: trusty

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - chmod +x gradlew

script:
  - ./gradlew --no-daemon clean bootJar
