name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '12'
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew clean assemble
      - name: Test
        run: |
          ./gradlew test
      - name: Analyse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonarqube